PAPER_CHAT_EXAMPLES = [
    {
        "thought": (
            "I will model this by assuming each observed student weight is drawn from a shared Normal "
            "distribution with unknown mean and unknown standard deviation. The latent variable weight_mean "
            "represents the true average student weight in the population. The latent variable weight_sigma "
            "captures heterogeneity among students and also absorbs small measurement noise. Because the user "
            "requested reasonably informative priors, I place a Normal prior on weight_mean centered at a plausible "
            "human adult mass and a LogNormal prior on weight_sigma to keep it positive while allowing moderate spread."
        ),
        "problem": "Given the weight of a bunch of students, infer the true mean of all students. Use reasonably informative priors and avoid overfitting to a tiny sample.",
        "data": {
            "num_students": 5,
            "student_weight": [72.0, 81.3, 76.5, 69.2, 85.1],
        },
        "goal": ["weight_mean"],
        "model": """import jax.numpy as jnp
import numpyro
import numpyro.distributions as dist

def model(data):
    w = jnp.array(data[\"student_weight\"])
    weight_mean = numpyro.sample(\"weight_mean\", dist.Normal(80.0, 20.0))
    weight_sigma = numpyro.sample(\"weight_sigma\", dist.LogNormal(jnp.log(10.0), jnp.log(2.0)))
    with numpyro.plate(\"students\", w.shape[0]):
        numpyro.sample(\"obs_weight\", dist.Normal(weight_mean, weight_sigma), obs=w)
""",
    },
    {
        "thought": (
            "I will use the same population-level latent variables (weight_mean and weight_sigma) as in the base "
            "weight example, then produce a posterior predictive sample for one new student from that same latent "
            "distribution. This lets the model share statistical strength from all observed students while still "
            "representing uncertainty for a future individual draw. The predictive quantity should be generated by "
            "sampling from Normal(weight_mean, weight_sigma), after conditioning on observed weights."
        ),
        "problem": "Given the weight of a bunch of students, infer the weight of a new student drawn from the same distribution, and preserve uncertainty in both mean and spread.",
        "data": {
            "num_students": 5,
            "student_weight": [72.0, 81.3, 76.5, 69.2, 85.1],
        },
        "goal": ["new_student_weight"],
        "model": """import jax.numpy as jnp
import numpyro
import numpyro.distributions as dist

def model(data):
    w = jnp.array(data[\"student_weight\"])
    weight_mean = numpyro.sample(\"weight_mean\", dist.Normal(70.0, 30.0))
    weight_sigma = numpyro.sample(\"weight_sigma\", dist.HalfStudentT(df=3.0, scale=5.0))
    with numpyro.plate(\"students\", w.shape[0]):
        numpyro.sample(\"obs_weight\", dist.Normal(weight_mean, weight_sigma), obs=w)
    numpyro.sample(\"new_student_weight\", dist.Normal(weight_mean, weight_sigma))
""",
    },
    {
        "thought": (
            "I will model user preference as a Bernoulli random variable whose logit is a linear combination of "
            "binary movie features. A latent coefficient vector beta captures how each feature pushes toward like or "
            "dislike. The training labels constrain beta through a Bernoulli-logit likelihood. Then, using the same beta, "
            "I can sample test_like values for unseen movies. This is a direct probabilistic analogue of logistic regression, "
            "with uncertainty carried through to predictions."
        ),
        "problem": "Given binary features of movies and observed training likes, predict if the user will like each test movie while accounting for uncertainty in feature effects.",
        "data": {
            "num_train": 4,
            "num_test": 2,
            "num_features": 3,
            "train_features": [[1, 0, 1], [0, 1, 1], [1, 1, 0], [0, 0, 1]],
            "train_like": [1, 0, 1, 0],
            "test_features": [[1, 0, 0], [0, 1, 0]],
        },
        "goal": ["test_like_1", "test_like_2"],
        "model": """import jax.numpy as jnp
import numpyro
import numpyro.distributions as dist

def model(data):
    x_train = jnp.array(data[\"train_features\"])
    y_train = jnp.array(data[\"train_like\"])
    x_test = jnp.array(data[\"test_features\"])
    beta = numpyro.sample(\"beta\", dist.Normal(0.0, 1.0).expand([x_train.shape[1]]).to_event(1))
    logits_train = x_train @ beta
    with numpyro.plate(\"train_items\", x_train.shape[0]):
        numpyro.sample(\"obs_like\", dist.Bernoulli(logits=logits_train), obs=y_train)
    logits_test = x_test @ beta
    for i in range(x_test.shape[0]):
        p_like = 1.0 / (1.0 + jnp.exp(-logits_test[i]))
        numpyro.deterministic(f"test_like_{i+1}", p_like)
""",
    },
    {
        "thought": (
            "I will use a latent factor model with one vector per user and one vector per movie. The dot product "
            "between user_features[u] and movie_features[m] provides a preference logit for that pair. This is a "
            "probabilistic matrix-factorization style model for binary feedback. Observed likes update both user and movie "
            "embeddings, and posterior uncertainty in those embeddings propagates into test-time predictions."
        ),
        "problem": "Collaborative filtering: infer latent user and movie features from sparse binary ratings and predict whether users will like future movies.",
        "data": {
            "num_users": 3,
            "num_movies": 4,
            "num_ratings": 5,
            "user": [1, 1, 2, 3, 3],
            "movie": [1, 3, 2, 2, 4],
            "like": [1, 0, 1, 0, 1],
            "num_test": 2,
            "test_user": [2, 1],
            "test_movie": [4, 2],
        },
        "goal": ["test_like_1", "test_like_2"],
        "model": """import jax.numpy as jnp
import numpyro
import numpyro.distributions as dist

def model(data):
    k = 5
    user_features = numpyro.sample(
        \"user_features\",
        dist.Normal(0.0, 1.0).expand([data[\"num_users\"], k]).to_event(2),
    )
    movie_features = numpyro.sample(
        \"movie_features\",
        dist.Normal(0.0, 1.0).expand([data[\"num_movies\"], k]).to_event(2),
    )

    for i in range(data[\"num_ratings\"]):
        u = data[\"user\"][i] - 1
        m = data[\"movie\"][i] - 1
        logit = jnp.dot(user_features[u], movie_features[m])
        numpyro.sample(f\"obs_like_{i+1}\", dist.Bernoulli(logits=logit), obs=data[\"like\"][i])

    for i in range(data[\"num_test\"]):
        u = data[\"test_user\"][i] - 1
        m = data[\"test_movie\"][i] - 1
        logit = jnp.dot(user_features[u], movie_features[m])
        p_like = 1.0 / (1.0 + jnp.exp(-logit))
        numpyro.deterministic(f"test_like_{i+1}", p_like)
""",
    },
    {
        "thought": (
            "I will build a hierarchical Beta-Binomial model. Each trial has a latent response probability, but trials "
            "of the same vaccine type should share information via type-level parameters. Type-level parameters are themselves "
            "regularized by global hyperparameters, allowing partial pooling across all types. This captures the user request "
            "that vaccines within a type are similar, while different types are not fully independent."
        ),
        "problem": "Vaccine trials: infer mean response rates for each trial type, using hierarchical sharing so small trial groups borrow strength from related groups.",
        "data": {
            "num_types": 3,
            "num_trials": 6,
            "trial_type": [1, 1, 2, 2, 3, 3],
            "num_subjects": [100, 120, 90, 110, 80, 95],
            "num_responded": [61, 70, 50, 64, 39, 49],
        },
        "goal": ["type_mean_1", "type_mean_2", "type_mean_3"],
        "model": """import numpyro
import numpyro.distributions as dist

def model(data):
    global_alpha = numpyro.sample(\"global_alpha\", dist.HalfNormal(5.0))
    global_beta = numpyro.sample(\"global_beta\", dist.HalfNormal(5.0))

    type_mean = []
    for t in range(data[\"num_types\"]):
        m_t = numpyro.sample(f\"type_mean_{t+1}\", dist.Beta(global_alpha, global_beta))
        k_t = numpyro.sample(f\"type_concentration_{t+1}\", dist.HalfNormal(20.0))
        a_t = m_t * k_t + 1e-3
        b_t = (1.0 - m_t) * k_t + 1e-3
        type_mean.append((a_t, b_t))

    for i in range(data[\"num_trials\"]):
        t = data[\"trial_type\"][i] - 1
        a_t, b_t = type_mean[t]
        p_i = numpyro.sample(f\"trial_rate_{i+1}\", dist.Beta(a_t, b_t))
        numpyro.sample(
            f\"obs_trial_{i+1}\",
            dist.Binomial(total_count=data[\"num_subjects\"][i], probs=p_i),
            obs=data[\"num_responded\"][i],
        )
""",
    },
    {
        "thought": (
            "I will model evaporation as a latent fraction between 0 and 1 that applies multiplicatively each day to remaining "
            "water mass. Starting from 1.0 kg, latent water decreases by multiplying by (1 - evaporation) each step. Observed "
            "measurements are noisy Normal observations around this latent trajectory. A Beta prior centered near 0.25 reflects "
            "the user's prior belief while still allowing broad uncertainty."
        ),
        "problem": "Water evaporation: infer the daily evaporation fraction from noisy remaining-water measurements, with prior belief that evaporation is around 0.25.",
        "data": {
            "num_days": 6,
            "measurements": [0.74, 0.56, 0.43, 0.31, 0.24, 0.18],
        },
        "goal": ["evaporation"],
        "model": """import numpyro
import numpyro.distributions as dist

def model(data):
    evaporation = numpyro.sample(\"evaporation\", dist.Beta(1.0, 3.0))
    meas_sigma = numpyro.sample(\"meas_sigma\", dist.HalfNormal(0.05))

    water = 1.0
    for i in range(data[\"num_days\"]):
        water = water * (1.0 - evaporation)
        numpyro.sample(f\"obs_day_{i+1}\", dist.Normal(water, meas_sigma), obs=data[\"measurements\"][i])
""",
    },
]


for ex in PAPER_CHAT_EXAMPLES:
    ex["input"] = (
        "INPUT\n"
        f"PROBLEM\n{ex['problem']}\n\n"
        f"DATA\n{ex['data']}\n\n"
        f"GOAL\n{ex['goal']}"
    )
    ex["output"] = (
        "OUTPUT\n"
        f"THOUGHT\n{ex['thought']}\n\n"
        "MODEL\n"
        f"```python\n{ex['model'].strip()}\n```"
    )
